ALTER TABLE [rd].[rds_user_rights] WITH CHECK 
ADD CONSTRAINT [FK_RDS_USER_REFERENCE_RDS_COMP] 
FOREIGN KEY([rc_id])
REFERENCES [rd].[rds_component] ([rc_id])
ON DELETE CASCADE
GO
ALTER TABLE [rd].[rds_user_rights] CHECK CONSTRAINT [FK_RDS_USER_REFERENCE_RDS_COMP]
GO
ALTER TABLE [rd].[rds_user_rights] WITH CHECK 
ADD CONSTRAINT [FK_RDS_USER_REFERENCE_RDS_USER2] 
FOREIGN KEY([ug_id])
REFERENCES [rd].[rds_user_group] ([ug_id])
GO
ALTER TABLE [rd].[rds_user_rights] CHECK CONSTRAINT [FK_RDS_USER_REFERENCE_RDS_USER2]
GO
