ALTER TABLE [rd].[town_suburb] WITH CHECK 
ADD CONSTRAINT [FK_TOWN_SUB_REFERENCE_SUBURBLO] 
FOREIGN KEY([sl_id])
REFERENCES [rd].[SuburbLocality] ([sl_id])
GO
ALTER TABLE [rd].[town_suburb] CHECK CONSTRAINT [FK_TOWN_SUB_REFERENCE_SUBURBLO]
GO
ALTER TABLE [rd].[town_suburb] WITH CHECK 
ADD CONSTRAINT [FK_TOWN_SUB_REFERENCE_TOWNCITY] 
FOREIGN KEY([tc_id])
REFERENCES [rd].[TownCity] ([tc_id])
GO
ALTER TABLE [rd].[town_suburb] CHECK CONSTRAINT [FK_TOWN_SUB_REFERENCE_TOWNCITY]
GO
