ALTER TABLE [rd].[TownCity] WITH CHECK 
ADD CONSTRAINT [FK_TOWNCITY_REF_609_REGION] 
FOREIGN KEY([region_id])
REFERENCES [rd].[region] ([region_id])
GO
ALTER TABLE [rd].[TownCity] CHECK CONSTRAINT [FK_TOWNCITY_REF_609_REGION]
GO
