ALTER TABLE [rd].[vehicle_rate] WITH CHECK 
  ADD CONSTRAINT [FK_VEHICLE__REF_1269_VEHICLE_] 
  FOREIGN KEY([vt_key])
    REFERENCES [rd].[vehicle_type] ([vt_key])
GO
ALTER TABLE [rd].[vehicle_rate] CHECK CONSTRAINT [FK_VEHICLE__REF_1269_VEHICLE_]
GO
ALTER TABLE [rd].[vehicle_rate] WITH CHECK 
  ADD CONSTRAINT [FK_VEHICLE__REF_1269_VEHICLE_1] 
  FOREIGN KEY([vt_key])
    REFERENCES [rd].[vehicle_type] ([vt_key])
GO
ALTER TABLE [rd].[vehicle_rate] CHECK CONSTRAINT [FK_VEHICLE__REF_1269_VEHICLE_1]
GO
