CREATE TABLE [odps].[national] (
    [nat_id]                          INT             IDENTITY (124, 1) NOT NULL,
    [ac_id]                           INT             NULL,
    [nat_ac_id_gst_GL]                INT             NULL,
    [nat_ac_id_whtax_GL]              INT             NULL,
    [nat_ac_id_postax_adj_GL]         INT             NULL,
    [nat_rural_post_gst_no]           VARCHAR (20)    NULL,
    [nat_gst_rate]                    DECIMAL (5, 2)  NULL,
    [nat_ird_no]                      VARCHAR (20)    NULL,
    [nat_rural_post_address]          VARCHAR (200)   NULL,
    [nat_rural_post_payer_name]       VARCHAR (200)   NULL,
    [nat_acc_percentage]              DECIMAL (5, 2)  NULL,
    [nat_standard_tax_rate]           DECIMAL (5, 2)  NULL,
    [nat_day_of_month]                SMALLINT        NULL,
    [nat_message_for_invoice]         VARCHAR (1000)  NULL,
    [nat_net_pct_change_warn]         DECIMAL (6, 2)  NULL,
    [nat_seq_no_for_keys]             INT             NULL,
    [nat_od_standard_gst_rate]        DECIMAL (10, 2) NULL,
    [nat_od_tax_rate_ir13]            DECIMAL (10, 2) NULL,
    [nat_od_tax_rate_no_ir13]         DECIMAL (10, 2) NULL,
    [ap_net_pay_clearing_account]     INT             NULL,
    [nat_effective_date]              DATETIME        NOT NULL,
    [nat_ac_id_contprice_GL]          INT             NULL,
    [nat_ac_id_NetPay_GL]             INT             NULL,
    [nat_ac_id_AccrualBalance_GL]     INT             NULL,
    [nat_PBU_code_postax_GL]          INT             NULL,
    [nat_PBU_code_whtax_GL]           INT             NULL,
    [nat_PBU_code_GST_GL]             INT             NULL,
    [nat_PBU_code_NetPay_GL]          INT             NULL,
    [nat_Invoice_Number_Prefix]       VARCHAR (20)    NULL,
    [______]                          VARBINARY (1)   NULL,
    [nat_PBU_code_AccrualBalance_GL]  INT             NULL,
    [nat_FreqAdj_DefaultCompType]     INT             NULL,
    [nat_ContAdj_DefaultCompType]     INT             NULL,
    [nat_ContAllow_DefaultComptype]   INT             NULL,
    [nat_Deductions_DefaultComptype]  INT             NULL,
    [nat_CourierPost_DefaultComptype] INT             NULL,
    [nat_AdPost_DefaultComptype]      INT             NULL,
    [nat_xp_defaultcomptype]          INT             NULL,
    [nat_pp_defaultcomptype]          INT             NULL,
    [cp_courierpost_defaultcomptype]  INT             NULL,
    [cp_reachmedia_defaultcomptype]   INT             NULL,
    [cp_publishing_defaultcomptype]   INT             NULL,
    [IRD_contact_name]                VARCHAR (30)    NULL,
    [IRD_contact_phone]               VARCHAR (20)    NULL,
    [IRD_contact_email]               VARCHAR (50)    NULL,
    CONSTRAINT [national(primary key)] PRIMARY KEY CLUSTERED ([nat_id] ASC),
    CONSTRAINT [FK_Payment_Component_Type] FOREIGN KEY ([nat_AdPost_DefaultComptype]) REFERENCES [odps].[Payment_Component_Type] ([pct_id]),
    CONSTRAINT [fk_xp_pct] FOREIGN KEY ([nat_xp_defaultcomptype]) REFERENCES [odps].[Payment_Component_Type] ([pct_id]),
    CONSTRAINT [Payment_Component_Type2] FOREIGN KEY ([nat_ContAdj_DefaultCompType]) REFERENCES [odps].[Payment_Component_Type] ([pct_id]),
    CONSTRAINT [Payment_Component_Type3] FOREIGN KEY ([nat_ContAllow_DefaultComptype]) REFERENCES [odps].[Payment_Component_Type] ([pct_id]),
    CONSTRAINT [Payment_Component_Type4] FOREIGN KEY ([nat_CourierPost_DefaultComptype]) REFERENCES [odps].[Payment_Component_Type] ([pct_id]),
    CONSTRAINT [Payment_Component_Type5] FOREIGN KEY ([nat_Deductions_DefaultComptype]) REFERENCES [odps].[Payment_Component_Type] ([pct_id]),
    CONSTRAINT [Payment_Component_Type6] FOREIGN KEY ([nat_FreqAdj_DefaultCompType]) REFERENCES [odps].[Payment_Component_Type] ([pct_id])
);

