CREATE TABLE [rd].[vehicle] (
    [vehicle_number]                INT             NOT NULL,
    [vt_key]                        INT             NULL,
    [ft_key]                        INT             NULL,
    [v_vehicle_make]                VARCHAR (20)    NULL,
    [v_vehicle_model]               VARCHAR (20)    NULL,
    [v_vehicle_year]                SMALLINT        NULL,
    [v_vehicle_registration_number] VARCHAR (8)     NULL,
    [v_vehicle_cc_rating]           SMALLINT        NULL,
    [v_road_user_charges_indicator] VARCHAR (1)     NULL,
    [v_purchased_date]              DATETIME        NULL,
    [v_purchase_value]              INT             NULL,
    [v_leased]                      VARCHAR (1)     NULL,
    [v_vehicle_month]               SMALLINT        NULL,
    [v_vehicle_transmission]        VARCHAR (1)     NULL,
    [vs_key]                        INT             NULL,
    [v_remaining_economic_life]     INT             NULL,
    [v_vehicle_speedo_kms]          INT             NULL,
    [v_vehicle_speedo_date]         DATETIME        NULL,
    [v_salvage_value]               INT             NULL,
    [v_vehicle_safety]              INT             NULL,
    [v_vehicle_emissions]           INT             NULL,
    [v_vehicle_consumption_rate]    DECIMAL (10, 1) NULL,
    CONSTRAINT [vehicle_cns] PRIMARY KEY CLUSTERED ([vehicle_number] ASC),
    CONSTRAINT [FK_fuel_type1] FOREIGN KEY ([ft_key]) REFERENCES [rd].[fuel_type] ([ft_key]),
    CONSTRAINT [FK_VEHICLE_REF_1997_VEHICLE_] FOREIGN KEY ([vs_key]) REFERENCES [rd].[vehicle_style] ([vs_key]),
    CONSTRAINT [FK_vehicle_type] FOREIGN KEY ([vt_key]) REFERENCES [rd].[vehicle_type] ([vt_key])
);

