CREATE TABLE [rd].[route_audit] (
    [contract_no]                      INT             NOT NULL,
    [ra_date_of_check]                 DATETIME        NOT NULL,
    [ra_time_started_sort]             DATETIME        NULL,
    [ra_time_finished_sort]            DATETIME        NULL,
    [ra_time_returned]                 DATETIME        NULL,
    [ra_time_departed]                 DATETIME        NULL,
    [ra_total_hours]                   DATETIME        NULL,
    [ra_meal_breaks]                   DATETIME        NULL,
    [ra_extra_time]                    DATETIME        NULL,
    [ra_final_hours]                   DATETIME        NULL,
    [ra_finish_odometer]               NUMERIC (10, 1) NULL,
    [ra_start_odometer]                NUMERIC (10, 1) NULL,
    [ra_extra_distance]                NUMERIC (5, 1)  NULL,
    [ra_othr_gds_before]               DATETIME        NULL,
    [ra_othr_gds_during]               DATETIME        NULL,
    [ra_othr_gds_after]                DATETIME        NULL,
    [ra_pr_before]                     DATETIME        NULL,
    [ra_pr_during]                     DATETIME        NULL,
    [ra_pr_after]                      DATETIME        NULL,
    [ra_total_distance]                NUMERIC (5, 1)  NULL,
    [ra_final_distance]                NUMERIC (5, 1)  NULL,
    [ra_frequency]                     VARCHAR (30)    NULL,
    [ra_contractor]                    VARCHAR (60)    NULL,
    [ra_employee]                      VARCHAR (60)    NULL,
    [ra_vehicle_make]                  VARCHAR (20)    NULL,
    [ra_vehicle_model]                 VARCHAR (20)    NULL,
    [ra_year]                          SMALLINT        NULL,
    [ra_registration_no]               VARCHAR (8)     NULL,
    [ra_fuel]                          VARCHAR (20)    NULL,
    [ra_cc_rating]                     SMALLINT        NULL,
    [ra_condition]                     VARCHAR (20)    NULL,
    [ra_rec_replace]                   DATETIME        NULL,
    [ra_tyre_size]                     VARCHAR (10)    NULL,
    [ra_gds_service]                   VARCHAR (1)     NULL,
    [ra_gds_service_sighted]           VARCHAR (1)     NULL,
    [ra_mv_insurance]                  VARCHAR (1)     NULL,
    [ra_cr_insurance]                  VARCHAR (1)     NULL,
    [ra_pl_insurance]                  VARCHAR (1)     NULL,
    [ra_insurance_sighted]             VARCHAR (1)     NULL,
    [ra_new_vehicle]                   VARCHAR (1)     NULL,
    [ra_vehicle_price]                 INT             NULL,
    [ra_vehicle_purchased]             DATETIME        NULL,
    [ra_mail_volume]                   VARCHAR (1)     NULL,
    [ra_mv_comments]                   VARCHAR (80)    NULL,
    [ra_adpost_volume]                 VARCHAR (1)     NULL,
    [ra_no_circular_drops]             SMALLINT        NULL,
    [ra_courierpost_volume]            VARCHAR (1)     NULL,
    [ra_cp_comments]                   VARCHAR (80)    NULL,
    [ra_no_reg_custs]                  SMALLINT        NULL,
    [ra_no_reg_custs_core_prods]       SMALLINT        NULL,
    [ra_other_custs]                   SMALLINT        NULL,
    [ra_rural_private_bags]            SMALLINT        NULL,
    [ra_private_bags]                  SMALLINT        NULL,
    [ra_closed_mails]                  SMALLINT        NULL,
    [ra_post_shops]                    SMALLINT        NULL,
    [ra_post_centres]                  SMALLINT        NULL,
    [ra_no_cmbs]                       SMALLINT        NULL,
    [ra_no_cmb_custs]                  SMALLINT        NULL,
    [ra_total_del_points]              SMALLINT        NULL,
    [ra_sorting_facilities]            VARCHAR (200)   NULL,
    [ra_sorting_case]                  VARCHAR (50)    NULL,
    [ra_sorting_comments]              VARCHAR (200)   NULL,
    [ra_length_sealed]                 NUMERIC (5, 1)  NULL,
    [ra_lenth_unsealed]                NUMERIC (5, 1)  NULL,
    [ra_total_length]                  NUMERIC (5, 1)  NULL,
    [ra_road_conditions]               VARCHAR (200)   NULL,
    [ra_suggested_improvements]        VARCHAR (200)   NULL,
    [ra_commencement_ok]               VARCHAR (1)     NULL,
    [ra_commencement_reason]           VARCHAR (200)   NULL,
    [ra_timetable_change]              VARCHAR (1)     NULL,
    [ra_route_ok]                      VARCHAR (1)     NULL,
    [ra_route_reason]                  VARCHAR (200)   NULL,
    [ra_deviations]                    VARCHAR (1)     NULL,
    [ra_deviation_in_desc]             VARCHAR (1)     NULL,
    [ra_deviation_reason]              VARCHAR (200)   NULL,
    [ra_description_uotdated]          VARCHAR (1)     NULL,
    [ra_volume]                        INT             NULL,
    [ra_safty_access_addresses]        VARCHAR (200)   NULL,
    [ra_safty_access_resolved_date]    DATETIME        NULL,
    [ra_saftey_access_actions]         VARCHAR (200)   NULL,
    [ra_safty_plan_completed]          VARCHAR (1)     NULL,
    [ra_safty_plan_completed_date]     DATETIME        NULL,
    [ra_safty_plan_actions]            VARCHAR (200)   NULL,
    [ra_safty_practices_exists]        VARCHAR (1)     NULL,
    [ra_safty_practices_resolved_date] DATETIME        NULL,
    [ra_safty_practices_actions]       VARCHAR (200)   NULL,
    [ra_fuel_used]                     NUMERIC (5, 1)  NULL,
    [ra_fuel_distance]                 NUMERIC (5, 1)  NULL,
    [ra_fuel_consumption]              NUMERIC (5, 1)  NULL,
    CONSTRAINT [route_audit_cns] PRIMARY KEY CLUSTERED ([contract_no] ASC, [ra_date_of_check] ASC)
);

