CREATE TABLE [rd].[temp_contract_renewals] (
    [contract_no]                          INT             NOT NULL,
    [contract_seq_number]                  INT             NOT NULL,
    [con_start_date]                       SMALLDATETIME   NULL,
    [con_rates_effective_date]             SMALLDATETIME   NULL,
    [con_rg_code_at_renewal]               INT             NULL,
    [con_expiry_date]                      SMALLDATETIME   NULL,
    [con_start_pay_date]                   SMALLDATETIME   NULL,
    [con_last_paid_date]                   SMALLDATETIME   NULL,
    [con_processing_hours_per_week]        DECIMAL (6, 2)  NULL,
    [con_renewal_benchmark_price]          DECIMAL (10, 2) NULL,
    [con_renewal_payment_value]            DECIMAL (10, 2) NULL,
    [con_relief_driver_name]               VARCHAR (40)    NULL,
    [con_relief_driver_address]            VARCHAR (200)   NULL,
    [con_relief_driver_home_phone]         VARCHAR (15)    NULL,
    [con_date_last_assigned]               SMALLDATETIME   NULL,
    [con_acceptance_flag]                  VARCHAR (1)     NULL,
    [con_distance_at_renewal]              DECIMAL (10, 2) NULL,
    [con_no_customers_at_renewal]          SMALLINT        NULL,
    [con_no_rural_private_bags_at_renewal] SMALLINT        NULL,
    [con_no_other_bags_at_renewal]         SMALLINT        NULL,
    [con_no_private_bags_at_renewal]       SMALLINT        NULL,
    [con_no_post_offices_at_renewal]       SMALLINT        NULL,
    [con_no_cmbs_at_renewal]               SMALLINT        NULL,
    [con_no_cmb_custs_at_renewal]          SMALLINT        NULL,
    [con_del_hrs_week_at_renewal]          DECIMAL (6, 2)  NULL,
    [con_volume_at_renewal]                INT             NULL
);

