ALTER TABLE [rd].[rds_user_id] WITH CHECK 
  ADD CONSTRAINT [FK_RDS_USER_REFERENCE_RDS_USER] 
  FOREIGN KEY([u_id])
    REFERENCES [rd].[rds_user] ([u_id])
  ON DELETE CASCADE
GO
ALTER TABLE [rd].[rds_user_id] CHECK CONSTRAINT [FK_RDS_USER_REFERENCE_RDS_USER]
GO
ALTER TABLE [rd].[rds_user_id_group] WITH CHECK 
  ADD CONSTRAINT [FK_RDS_USER_REFERENCE_RDS_USER_ID] 
  FOREIGN KEY([ui_id])
    REFERENCES [rd].[rds_user_id] ([ui_id])
GO
