ALTER TABLE [rd].[Road_Suburb] WITH CHECK 
ADD CONSTRAINT [FK_ROAD_SUB_REF_600_SUBURBLO] 
FOREIGN KEY([sl_id])
REFERENCES [rd].[SuburbLocality] ([sl_id])
GO
ALTER TABLE [rd].[Road_Suburb] CHECK CONSTRAINT [FK_ROAD_SUB_REF_600_SUBURBLO]
GO
ALTER TABLE [rd].[Road_Suburb] WITH CHECK 
ADD CONSTRAINT [FK_ROAD_SUB_REF_606_ROAD] 
FOREIGN KEY([road_id])
REFERENCES [rd].[Road] ([road_id])
GO
ALTER TABLE [rd].[Road_Suburb] CHECK CONSTRAINT [FK_ROAD_SUB_REF_606_ROAD]
GO
