ALTER TABLE [rd].[Road] WITH CHECK 
ADD CONSTRAINT [FK_ROAD_REF_ROAD_SUFFIX] 
FOREIGN KEY([rs_id])
REFERENCES [rd].[road_suffix] ([rs_id])
GO
ALTER TABLE [rd].[Road] CHECK CONSTRAINT [FK_ROAD_REF_ROAD_SUFFIX]
GO
ALTER TABLE [rd].[Road] WITH CHECK 
ADD CONSTRAINT [FK_ROAD_REFERENCE_ROAD_TYP] 
FOREIGN KEY([rt_id])
REFERENCES [rd].[Road_Type] ([rt_id])
GO
ALTER TABLE [rd].[Road] CHECK CONSTRAINT [FK_ROAD_REFERENCE_ROAD_TYP]
GO
ALTER TABLE [rd].[Road] WITH CHECK 
ADD CONSTRAINT [FK_ROAD_REFERENCE_ROAD_TYP1] 
FOREIGN KEY([rt_id])
REFERENCES [rd].[Road_Type] ([rt_id])
GO
ALTER TABLE [rd].[Road] CHECK CONSTRAINT [FK_ROAD_REFERENCE_ROAD_TYP1]
GO
