/****** Object:  Table [rd].[route_audit]    Script Date: 08/05/2008 15:01:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [rd].[route_audit](
	[contract_no] [int] NOT NULL,
	[ra_date_of_check] [datetime] NOT NULL,
	[ra_time_started_sort] [datetime] NULL,
	[ra_time_finished_sort] [datetime] NULL,
	[ra_time_returned] [datetime] NULL,
	[ra_time_departed] [datetime] NULL,
	[ra_total_hours] [datetime] NULL,
	[ra_meal_breaks] [datetime] NULL,
	[ra_extra_time] [datetime] NULL,
	[ra_final_hours] [datetime] NULL,
	[ra_finish_odometer] [numeric](10, 1) NULL,
	[ra_start_odometer] [numeric](10, 1) NULL,
	[ra_extra_distance] [numeric](5, 1) NULL,
	[ra_othr_gds_before] [datetime] NULL,
	[ra_othr_gds_during] [datetime] NULL,
	[ra_othr_gds_after] [datetime] NULL,
	[ra_pr_before] [datetime] NULL,
	[ra_pr_during] [datetime] NULL,
	[ra_pr_after] [datetime] NULL,
	[ra_total_distance] [numeric](5, 1) NULL,
	[ra_final_distance] [numeric](5, 1) NULL,
	[ra_frequency] [varchar](30) COLLATE Latin1_General_CI_AS NULL,
	[ra_contractor] [varchar](60) COLLATE Latin1_General_CI_AS NULL,
	[ra_employee] [varchar](60) COLLATE Latin1_General_CI_AS NULL,
	[ra_vehicle_make] [varchar](20) COLLATE Latin1_General_CI_AS NULL,
	[ra_vehicle_model] [varchar](20) COLLATE Latin1_General_CI_AS NULL,
	[ra_year] [smallint] NULL,
	[ra_registration_no] [varchar](8) COLLATE Latin1_General_CI_AS NULL,
	[ra_fuel] [varchar](20) COLLATE Latin1_General_CI_AS NULL,
	[ra_cc_rating] [smallint] NULL,
	[ra_condition] [varchar](20) COLLATE Latin1_General_CI_AS NULL,
	[ra_rec_replace] [datetime] NULL,
	[ra_tyre_size] [varchar](10) COLLATE Latin1_General_CI_AS NULL,
	[ra_gds_service] [varchar](1) COLLATE Latin1_General_CI_AS NULL,
	[ra_gds_service_sighted] [varchar](1) COLLATE Latin1_General_CI_AS NULL,
	[ra_mv_insurance] [varchar](1) COLLATE Latin1_General_CI_AS NULL,
	[ra_cr_insurance] [varchar](1) COLLATE Latin1_General_CI_AS NULL,
	[ra_pl_insurance] [varchar](1) COLLATE Latin1_General_CI_AS NULL,
	[ra_insurance_sighted] [varchar](1) COLLATE Latin1_General_CI_AS NULL,
	[ra_new_vehicle] [varchar](1) COLLATE Latin1_General_CI_AS NULL,
	[ra_vehicle_price] [int] NULL,
	[ra_vehicle_purchased] [datetime] NULL,
	[ra_mail_volume] [varchar](1) COLLATE Latin1_General_CI_AS NULL,
	[ra_mv_comments] [varchar](80) COLLATE Latin1_General_CI_AS NULL,
	[ra_adpost_volume] [varchar](1) COLLATE Latin1_General_CI_AS NULL,
	[ra_no_circular_drops] [smallint] NULL,
	[ra_courierpost_volume] [varchar](1) COLLATE Latin1_General_CI_AS NULL,
	[ra_cp_comments] [varchar](80) COLLATE Latin1_General_CI_AS NULL,
	[ra_no_reg_custs] [smallint] NULL,
	[ra_no_reg_custs_core_prods] [smallint] NULL,
	[ra_other_custs] [smallint] NULL,
	[ra_rural_private_bags] [smallint] NULL,
	[ra_private_bags] [smallint] NULL,
	[ra_closed_mails] [smallint] NULL,
	[ra_post_shops] [smallint] NULL,
	[ra_post_centres] [smallint] NULL,
	[ra_no_cmbs] [smallint] NULL,
	[ra_no_cmb_custs] [smallint] NULL,
	[ra_total_del_points] [smallint] NULL,
	[ra_sorting_facilities] [varchar](200) COLLATE Latin1_General_CI_AS NULL,
	[ra_sorting_case] [varchar](50) COLLATE Latin1_General_CI_AS NULL,
	[ra_sorting_comments] [varchar](200) COLLATE Latin1_General_CI_AS NULL,
	[ra_length_sealed] [numeric](5, 1) NULL,
	[ra_lenth_unsealed] [numeric](5, 1) NULL,
	[ra_total_length] [numeric](5, 1) NULL,
	[ra_road_conditions] [varchar](200) COLLATE Latin1_General_CI_AS NULL,
	[ra_suggested_improvements] [varchar](200) COLLATE Latin1_General_CI_AS NULL,
	[ra_commencement_ok] [varchar](1) COLLATE Latin1_General_CI_AS NULL,
	[ra_commencement_reason] [varchar](200) COLLATE Latin1_General_CI_AS NULL,
	[ra_timetable_change] [varchar](1) COLLATE Latin1_General_CI_AS NULL,
	[ra_route_ok] [varchar](1) COLLATE Latin1_General_CI_AS NULL,
	[ra_route_reason] [varchar](200) COLLATE Latin1_General_CI_AS NULL,
	[ra_deviations] [varchar](1) COLLATE Latin1_General_CI_AS NULL,
	[ra_deviation_in_desc] [varchar](1) COLLATE Latin1_General_CI_AS NULL,
	[ra_deviation_reason] [varchar](200) COLLATE Latin1_General_CI_AS NULL,
	[ra_description_uotdated] [varchar](1) COLLATE Latin1_General_CI_AS NULL,
	[ra_volume] [int] NULL,
	[ra_safty_access_addresses] [varchar](200) COLLATE Latin1_General_CI_AS NULL,
	[ra_safty_access_resolved_date] [datetime] NULL,
	[ra_saftey_access_actions] [varchar](200) COLLATE Latin1_General_CI_AS NULL,
	[ra_safty_plan_completed] [varchar](1) COLLATE Latin1_General_CI_AS NULL,
	[ra_safty_plan_completed_date] [datetime] NULL,
	[ra_safty_plan_actions] [varchar](200) COLLATE Latin1_General_CI_AS NULL,
	[ra_safty_practices_exists] [varchar](1) COLLATE Latin1_General_CI_AS NULL,
	[ra_safty_practices_resolved_date] [datetime] NULL,
	[ra_safty_practices_actions] [varchar](200) COLLATE Latin1_General_CI_AS NULL,
 CONSTRAINT [route_audit_cns] PRIMARY KEY CLUSTERED 
(
	[contract_no] ASC,
	[ra_date_of_check] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
