/*
create procedure rd.sp_GetRdsUserGroup(@AL_PARENT_ID1 int)
AS
BEGIN
set CONCAT_NULL_YIELDS_NULL off
  select LABEL=RDS_USER_GROUP.UG_NAME,ID=RDS_USER_GROUP.UG_ID,ACCOUNT=RDS_USER_GROUP.UG_ID,PARENT_ID1=@AL_PARENT_ID1,
    PICTINDEX=2 from RDS_USER_GROUP where @AL_PARENT_ID1 = 1 union select LABEL=RDS_USER.U_NAME,
    ID=RDS_USER_ID.UI_ID,ACCOUNT=RDS_USER.U_ID,PARENT_ID1=@AL_PARENT_ID1,PICTINDEX=3 from RDS_USER,
    RDS_USER_ID where @AL_PARENT_ID1 = 2 and RDS_USER.U_ID = RDS_USER_ID.U_ID union select LABEL=RDS_MAINTENANCE_TABLE.MT_NAME,
    ID=RDS_MAINTENANCE_TABLE.MT_ID,ACCOUNT=0,PARENT_ID1=@AL_PARENT_ID1,PICTINDEX=5 from
    RDS_MAINTENANCE_TABLE where @AL_PARENT_ID1 = 3
end
*/
create procedure [rd].[sp_GetRdsUserInfo](@AL_PARENT_ID1 int,@AL_PARENT_ID2 int)
AS
BEGIN
  select LABEL=RDS_USER.U_NAME,ID=RDS_USER_ID.UI_ID,ACCOUNT=RDS_USER.U_ID,PARENT_ID1=@AL_PARENT_ID1,
    PARENT_ID2=@AL_PARENT_ID2,PICTINDEX=3 from RDS_USER,RDS_USER_GROUP,RDS_USER_ID,RDS_USER_ID_GROUP where
    (RDS_USER_ID.U_ID = RDS_USER.U_ID) and(RDS_USER_ID_GROUP.UI_ID = RDS_USER_ID.UI_ID) and
    (RDS_USER_ID_GROUP.UG_ID = RDS_USER_GROUP.UG_ID) and((RDS_USER_GROUP.UG_ID = @AL_PARENT_ID1) and(@AL_PARENT_ID2 = 1)) union
  select RDS_USER_GROUP.UG_NAME,RDS_USER_GROUP.UG_ID,0,@AL_PARENT_ID1,@AL_PARENT_ID2,PICTINDEX=2 from
    RDS_USER,RDS_USER_GROUP,RDS_USER_ID,RDS_USER_ID_GROUP where(RDS_USER_ID.U_ID = RDS_USER.U_ID) and
    (RDS_USER_ID_GROUP.UI_ID = RDS_USER_ID.UI_ID) and(RDS_USER_ID_GROUP.UG_ID = RDS_USER_GROUP.UG_ID) and
    ((RDS_USER_ID_GROUP.UI_ID = @AL_PARENT_ID1) and(@AL_PARENT_ID2 = 2)) union select REGION.RGN_NAME,REGION.REGION_ID,
    0,@AL_PARENT_ID1,@AL_PARENT_ID2,PICTINDEX=2 from REGION where @AL_PARENT_ID2 = 3 and @AL_PARENT_ID1 = 1
end